// import Head from "next/head";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { ThemeProvider } from "next-themes";
import { user } from "@/lib/api/user";
import "../globals.css";
import UserCard from "@/components/userCard";
// import Navbar from "@/components/navbar";
// import Footer from "@/components/ui/footer";
// import Providers from "./providers";
// import { Link } from "lucide-react";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });
export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Layout({ children, }: { children: React.ReactNode; }) {
    const userdata = await user({ limit: 10, page: 1 })
    // console.log("userdata", userdata)

    return (
        <html lang="en" suppressHydrationWarning={true}>

            <body className="geist_e531dabc-module__QGiZLq__variable geist_mono_68a01160-module__YLcDdW_..." >


                <div className="p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-8 max-w-4/5 mx-auto">
                    {userdata.users.map((user) => (
                        <div key={user.id} >
                            <UserCard userpost={user} />
                        </div>
                    ))}
                </div>
                {children}

            </body>
        </html>
    );
}
